# azure-pipelines-function.yml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Use Python 3.x'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    npm install -g azure-functions-core-tools@3 --unsafe-perm true
  displayName: 'Install Dependencies and Azure Functions Core Tools'

- script: |
    func azure functionapp publish $(FUNCTION_APP_NAME)
  displayName: 'Deploy Azure Function App'
