# azure-pipelines-test-report.yml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Use Python 3.x'

- script: |
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pytest --junitxml=test-results.xml
  displayName: 'Run Tests with JUnit Report'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test-results.xml'
    testRunTitle: 'Pytest Results'
  displayName: 'Publish Test Results'
